host: 0.0.0.0
name: "A voice from the Cloud"
title: "A voice from the Cloud"
permalink: /blog/:title
MY_URL: https://gianarb.it
markdown: kramdown
collections:
  my_talks:
    sort_by: lesson
  courses:
    output: true
    permalink: /:collection/:name
