host: 0.0.0.0
name: "A voice from the Cloud"
title: "A voice from the Cloud"
permalink: /blog/:title
MY_URL: https://gianarb.it
markdown: kramdown
collections:
  my_talks:
    sort_by: lesson
    output: true
exclude:
  - package.json
  - package-lock.json
  - gemset.nix
  - default.nix
  - Makefile
  - node_modules
  - vendor/bundle
sass:
  sass_dir: _sass
